// src/pages/stepsPlugins/llmResponse/index.ts
import { register } from '../registry';
import { PLUGIN_CATEGORIES } from '../registry';
import { LLMResponseEditor } from './LLMResponseEditor';
import { LLMResponseResult } from './LLMResponseResult';
import { LLMResponseViewer } from './LLMResponseViewer';

register({
  type: 'llm-response',
  name: 'LLM Response',
  Viewer: LLMResponseViewer,
  Editor: LLMResponseEditor,
  ResultRenderer: LLMResponseResult,
  category: PLUGIN_CATEGORIES.CONTENT,
  description: 'Generate and display content using LLM',
  defaultConfig: {
    title: 'LLM Response',
    description: 'Content generated by AI',
    promptTemplate: 'Generate {{type}} about {{topic}}',
    mockResponse: false,
    responseSampleType: 'json',
    responseSample: '{\n  "title": "Sample Response",\n  "content": "This is a sample response"\n}'
  }
});